$('.slider').owlCarousel({
    loop:true,
    margin:20,
	nav:true,
	navText:false,
	dots:true,
	responsive:{
		0:{
            items:1,
            nav:true
        },
		500:{
            items:1,
            nav:true
        },
		
		800:{
            items:2,
            nav:true
        },
		1200:{
            items:2,
            nav:true
        }
    }
});